services:
  devbox:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    container_name: alchemist-lab
    volumes:
      - ~/Projects:/home/workspace/projects
    environment:
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dev
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=dev
    env_file:
      - ../.envrc
    tty: true
    stdin_open: true
    ports:
      - "2222:22"
    networks:
      - devnet
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: alchemist-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devnet

volumes:
  postgres_data:

networks:
  devnet:
    driver: bridge
